language: php
php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate

script: vendor/bin/phpunit